---
- hosts: centos
  become: true
  tasks:
    - name: Install Packages
      yum: name={{ item }} state=latest
      with_items:
         - vim
         - git
         - curl
# set DNS      
    - nmcli:
      conn_name: ens192
      type: ethernet
      dns4:
        - 192.168.88.138
        - 192.168.88.139
      state: present
    
  handlers:
    - name: restart networking
      service: name=network state=restarted
  
