- hosts: ubuntu 
  become: true
  tasks:
    - shell: sudo useradd nagios
    - name: Install Packages
      apt: name={{ item }} state=latest
      with_items:
         - python
         - vim
         - unzip
         - openssl
         - git
         - wget
         - curl
         - htop
         - tmux
