- hosts: ubuntu 
  become: true
  tasks:
    - shell: sudo useradd nagios
    - name: Install Packages
      apt: name={{ item }} state=latest
      with_items:
         - vim
         - build-essential
         - libgd2-xpm-dev
         - unzip
         - openssl
         - libssl-dev
         - git
         - curl
         - htop
    - shell: cd /home/rusty | curl -L -O http://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz | tar zxf nagios-plugins-*.tar.gz | cd nagios-plugins-* | ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl | make | sudo make install
    - shell: cd /home/rusty | curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz | tar zxf nrpe-*.tar.gz | cd nrpe-* | ./configure --enable-command-args --with-nagios-user=nagios --with-nagios-group=nagios --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu | make all | sudo make install | sudo make install-config | sudo make install-init
    - copy:
        src: /home/rusty/playbooks/nagios/ref_files/nrpe.cfg
        dest: /etc/nagios/nrpe.cfg
        owner: nagios
        group: nagios
        mode: 600
    - shell: sudo systemctl start nrpe | sudo systemctl enable nrpe
    - shell: sudo ufw allow 5666/tcp     
